"""The rules and the registry that holds them.

A rule declares its id, label, message, languages and scope, so the report,
the config and the CLI can all read those from one place.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from .config import CHECKED, Config, TS_LIKE, C_LIKE, matches_any
from .source import Source, grep_code, grep_comments, hit, line_of, load_source


MAX_HITS_PER_RULE = 5


@dataclass
class Violation:
    rule: str
    hits: list[str]


CODE_LIKE_COMMENT = re.compile(
    r"^\s*(//|#|\*)?\s*(const |let |var |return\b|if \(|for \(|while \(|import |from \S+ import|def |class |await |"
    r"\w+(\.\w+)*\(.*\)\s*;?\s*$|\w+\s*=\s*[^=].*;?\s*$|[}{]\s*$)"
)


NARRATION = re.compile(
    r"\b(added|updated|fixed|changed|removed|modified|refactored|now we|here we|this (function|method|class|file|helper) "
    r"(is|does|handles|returns|will)|helper (function|method)|utility function|initiali[sz]e the|import(s|ing)? (the|for)|"
    r"call(s|ing) the|loop (over|through) the|check(s|ing) (if|whether) the|increment|declare)\b",
    re.IGNORECASE,
)


LICENSE_NOTICE = re.compile(r"copyright|\(c\)\s*\d{4}|licen[cs]ed?\b|SPDX-License-Identifier|all rights reserved", re.I)


PROTOCOL_EXC = re.compile(r"\b(StopIteration|StopAsyncIteration|GeneratorExit)\b")


PROSE_ASSIGNMENT = re.compile(r"=\s*[A-Za-z]+(\s+[A-Za-z]+){2,}\s*$")


NO_CODE_PUNCTUATION = re.compile(r"^[^;(){}\[\]<>=\"'`]*$")


GENERATED_MARKER = re.compile(r"@generated|code generated by|do not edit|auto-?generated|automatically generated", re.I)


@dataclass(frozen=True)
class Rule:
    """A rule is data: the report, the config and the CLI all read it from here."""
    id: str
    label: str
    message: str
    check: Callable[["Source", "Config", Path], list[str]]
    languages: frozenset[str] | None = None
    whole_file: bool = False

    def applies_to(self, suffix: str) -> bool:
        return self.languages is None or suffix in self.languages


RULES: list[Rule] = []
BY_ID: dict[str, Rule] = {}


def rule(id: str, label: str, message: str, languages: frozenset[str] | None = None, whole_file: bool = False):
    def register(check):
        entry = Rule(id, label, message, check, languages, whole_file)
        RULES.append(entry)
        BY_ID[id] = entry
        return check
    return register


@rule("debug-output", "debug output",
      "Debug output left behind. Remove it or use the project logger.")
def _debug_output(src, cfg, root):
    if matches_any(src.path, cfg.allow_console, root):
        return []
    hits = grep_code(src, r"^\s*(console\.(log|debug|info|trace)\(|print\(|pprint\(|dbg!\(|var_dump\(|println!\(|fmt\.Println\(|System\.out\.print|Console\.WriteLine\(|debugger\b)")
    return [h for h in hits if not re.search(r"\bfile\s*=", h)]


@rule("narration-comment", "comment narrates or restates code: delete",
      "Comment narrates the edit or restates the code. Delete it; the code says it.")
def _narration(src, cfg, root):
    # A comment narrates the edit when the verb opens it. Mid-sentence it is ordinary prose.
    hits = []
    for c in src.comments:
        for k, l in enumerate(c.text.split("\n")):
            body = re.sub(r"^\s*(/\*\*?|\*/?|//|#)\s*", "", l)
            if NARRATION.match(body) and not re.search(r"https?://|@param|@returns|@throws|generated by|auto-?generated|do not edit", l, re.I):
                hits.append(hit(src, c.line + k)); break
    return hits


@rule("banner-comment", "banner comment: delete",
      "Section banner comment. Delete it; use blank lines and function boundaries.")
def _banner(src, cfg, root):
    rx = re.compile(r"^\s*(//|#|/\*|\*)\s*[-=*#~_]{4,}")
    hits = []
    for c in src.comments:
        if LICENSE_NOTICE.search(c.text):
            continue
        for k, l in enumerate(c.text.split("\n")):
            if rx.search(l):
                hits.append(hit(src, c.line + k)); break
    return hits


@rule("closing-brace-comment", "closing-brace comment: delete",
      "Closing-brace comment. If the block is too long to track, shorten the block.", languages=frozenset(C_LIKE))
def _closing_brace(src, cfg, root):
    return [hit(src, i + 1) for i, l in enumerate(src.lines) if re.search(r"\}\s*//\s*(end|close|\}|/?\w+\s*$)", l)]


@rule("todo-marker", "TODO/FIXME: do it or remove",
      "TODO/FIXME left in delivered code. Do it now, or track it outside the code.")
def _todo(src, cfg, root):
    return [] if cfg.allow_todo else grep_comments(src, r"\b(TODO|FIXME|XXX|HACK)\b")


def is_prose(body: str) -> bool:
    """A line with no code punctuation that reads as a sentence is prose, whatever word opens it."""
    if not NO_CODE_PUNCTUATION.match(body):
        return False
    return body.rstrip().endswith(".") or len(body.split()) >= 4


@rule("commented-code", "commented-out code: delete",
      "Commented-out code. Delete it; version control remembers.")
def _commented_code(src, cfg, root):
    hits = []
    for c in src.comments:
        body = re.sub(r"^\s*(//|#|/\*|\*)\s?", "", c.text.split("\n")[0])
        if CODE_LIKE_COMMENT.match(body) and not re.match(r"^\s*(@|https?://)", body) and len(body) > 3 \
                and not PROSE_ASSIGNMENT.search(body) and not body.startswith("   ") \
                and not is_prose(body):
            hits.append(hit(src, c.line))
    return hits


@rule("redundant-docstring", "docstring restates signature: delete",
      "Docstring restates the signature. Delete it or write what the name cannot say.")
def _redundant_doc(src, cfg, root):
    return grep_comments(src, r"^\s*(/\*\*?|///|#|\*|//)\s*(gets?|sets?|returns?|creates?|initiali[sz]es?|constructor|default constructor)\s+(the\s+|a\s+)?\w+\.?\s*(\*/)?\s*$")


@rule("suppressed-check", "silenced check: fix the cause",
      "A check was silenced. Fix the cause; if the check is wrong, fix the check in its own commit.")
def _suppressed(src, cfg, root):
    hits = grep_comments(src, r"@ts-ignore|@ts-expect-error|@ts-nocheck|eslint-disable|#\s*noqa|type:\s*ignore|pylint:\s*disable|prettier-ignore|phpcs:ignore|nolint")
    return hits + grep_code(src, r"@SuppressWarnings|#pragma warning disable|\[SuppressMessage")


@rule("weak-type", "any / loose type: write the real type",
      "`any`, `as unknown as`, or a loose type. Write the real type.", languages=frozenset(TS_LIKE))
def _weak_type(src, cfg, root):
    return grep_code(src, r"\bas any\b|:\s*any\b|<any>|\bas unknown as\b|Function\b(?!\s*\()|:\s*object\b")


@rule("non-null-assertion", "`!` assertion: narrow explicitly",
      "Non-null assertion hides a real nullability. Narrow it explicitly.", languages=frozenset(TS_LIKE))
def _non_null(src, cfg, root):
    return grep_code(src, r"[\w\)\]]!(?=[\.\)\[,;\s])(?!=)")


@rule("skipped-test", "skipped or focused test",
      "Skipped, focused, or ignored test. An ignored test is an unanswered question.")
def _skipped_test(src, cfg, root):
    # A conditional skip is a platform guard, and .fit( is not a focused test.
    return grep_code(src, r"\b(it|test|describe)\.(skip|only|todo)\(\s*['\"`]|\bx(it|describe|test)\(|(?<![.\w])f(it|describe)\(|@(pytest\.mark|unittest)\.skip(?![A-Za-z])|@Ignore\b|@Disabled\b|t\.Skip\(")


@rule("swallowed-error", "empty catch: handle or rethrow",
      "Empty catch/except. Handle it, rethrow with context, or let it propagate.")
def _empty_catch(src, cfg, root):
    joined = "\n".join(src.code_lines)
    hits = []
    for m in re.finditer(r"catch\s*(\([^)]*\))?\s*\{\s*\}|except[^:\n]*:\s*\n\s*pass\b|rescue\s*\n\s*end\b", joined):
        if PROTOCOL_EXC.search(m.group(0)):
            continue
        hits.append(hit(src, joined[:m.start()].count("\n") + 1))
    return hits


@rule("hardcoded-secret", "hardcoded secret: use env",
      "Credential in source. Read it from the environment or a secret store.")
def _secret(src, cfg, root):
    return [hit(src, i + 1) for i, l in enumerate(src.lines)
            if re.search(r"(api[_-]?key|secret|passw(or)?d|token|bearer|private[_-]?key)\w*\s*(:\s*string\s*)?[:=]\s*[\"'][A-Za-z0-9_\-/+=]{12,}[\"']", l, re.I)
            and not re.search(r"process\.env|os\.environ|getenv|\$\{|<[A-Z_]+>|example|placeholder|xxx", l, re.I)]


@rule("comment-density", "too many comment lines: rename and extract",
      "More comment lines than the ratio allows. Rename and extract instead of explaining.", whole_file=True)
def _density(src, cfg, root):
    code = sum(1 for l in src.code_lines if l.strip())
    comment = sum(c.text.count("\n") + 1 for c in src.comments)
    if code >= 40 and comment > code * cfg.max_comment_ratio:
        return [f"{comment} comment lines for {code} code lines"]
    return []


EMPHASIS = {"ALWAYS", "NEVER", "MUST", "ONLY", "CRITICAL", "IMPORTANT", "WARNING", "DANGER", "CAUTION",
            "BEWARE", "ATTENTION", "MANDATORY", "FORBIDDEN", "URGENT", "CAREFUL", "NOTE", "REMEMBER"}


CAPS_RUN = re.compile(r"\b[A-Z][A-Z0-9_]+(?:\s+[A-Z][A-Z0-9_]+){2,}\b")


ACRONYM_OK = {"API", "URL", "URI", "ID", "IDS", "UPC", "ISRC", "ISWC", "JSON", "XML", "HTTP", "HTTPS", "SQL", "CSV", "PDF", "UTC", "CPU", "RAM", "DSP", "SSR", "CSR", "UI", "UX", "JWT", "TTL", "CDN", "DNS", "IP", "TCP", "AWS", "S3", "CLI", "ENV", "OK", "MB", "GB", "KB"}


def shouts(line: str) -> bool:
    """An uppercase run only shouts when it is emphasis rather than a run of known identifiers."""
    if set(re.findall(r"(?<![-\w])[A-Z]{3,}(?![-\w])", line)) & EMPHASIS:
        return True
    return any(any(w not in ACRONYM_OK for w in run.group(0).split()) for run in CAPS_RUN.finditer(line))


@rule("comment-typography", "glyph in comment: plain text",
      "Em dash, middle dot, bullet glyph, emoji or icon in a comment. Plain sentences only.")
def _comment_typography(src, cfg, root):
    return grep_comments(src, "[\u2014\u2013\u00b7\u2022\u2192\u2713\u2717\u2705\u274c\u26a0\U0001F300-\U0001FAFF]")


@rule("comment-shouting", "ALL CAPS in comment: rewrite plainly",
      "ALL CAPS emphasis in a comment. Say it in a plain sentence.")
def _comment_shouting(src, cfg, root):
    hits = []
    for c in src.comments:
        if LICENSE_NOTICE.search(c.text):
            continue
        for k, l in enumerate(c.text.split("\n")):
            if shouts(l):
                hits.append(hit(src, c.line + k)); break
    return hits


@rule("phase-label", "task/phase label in comment: remove",
      "Task, phase or prompt label in a comment. That is the conversation's context, not the code's. Remove it.")
def _phase_label(src, cfg, root):
    return grep_comments(src, r"\b(phase|step|task|sprint|ticket|milestone|iteration)\s*[A-Z]?\d+[A-Z0-9]+\b|\b[A-Z]\d{1,3}[A-Z]?\b(?=\s+\w*(import|cutover|migrat|ingest|rollout|stage|flow|materializ))|\bper (the|our|my) (plan|prompt|conversation|spec)\b")


@rule("header-essay", "file header over four lines: move detail to the functions",
      "File header comment runs past four lines. Say what the module owns and what it deliberately does not.")
def _header_essay(src, cfg, root):
    for c in src.comments:
        if c.line > 3:
            break
        body = [l for l in c.text.split("\n") if re.sub(r"^\s*(/\*\*?|\*/?|//|#)\s*", "", l).strip()]
        if len(body) > 4:
            return [hit(src, c.line)]
    return []


def is_generated(src: Source) -> bool:
    """A generated file carries its marker up top and is not the author's to clean."""
    return any(c.line <= 5 and GENERATED_MARKER.search(c.text) for c in src.comments)


def check_file(path: Path, cfg: Config, root: Path, only_lines: set[int] | None = None) -> list[Violation]:
    if path.suffix not in CHECKED or not path.is_file() or matches_any(path, cfg.ignore, root):
        return []
    src = load_source(path)
    if is_generated(src):
        return []
    out = []
    for r in RULES:
        if r.id in cfg.disabled or not r.applies_to(path.suffix):
            continue
        if only_lines is not None and r.whole_file:
            # A whole-file property cannot be what one targeted edit introduced.
            continue
        hits = r.check(src, cfg, root)
        if not hits:
            continue
        if only_lines is not None:
            hits = [h for h in hits if line_of(h) in only_lines]
            if not hits:
                continue
        out.append(Violation(r.id, hits[:MAX_HITS_PER_RULE]))
    return out
